version: '2'
services:
    memcached:
        restart: always
        image: memcached:alpine
        ports:
            - "11211:11211"
    web:
        restart: always
        build: .
        ports:
            - "8000:80"
        links:
            - memcached

