version: '2'
services:
    https-portal:
      image: steveltn/https-portal:1.0.0
      ports:
        - '80:80'
        - '443:443'
      links:
        - web
      restart: always
      environment:
        DOMAINS: 'kuropen.org -> http://web'
        STAGE: 'production'
    redis:
        restart: always
        image: redis:alpine
        ports:
            - "6379:6379"
    web:
        restart: always
        build: .
        links:
            - redis

